### ISSUE TITLE
Envoi d'email transactionnel avec en attachement PDF

### ISSUE THREAD

**Issue by bamboolix** [mailjet/mailjet-apiv3-php#26]
Bonjour, 

J'intègre l'API MAiljet pour de nouveaux comptes V3 de mes clients. 
En l'occurence je suis en train de changer la classe qui envoie des emails transactionnels.

J'arrive à envoyer un mail avec un fichier txt attaché comme dans l'exemple : http://dev.mailjet.com/guides/?php#sending-with-attached-files
Mais impossible d'envoyer un mail avec un fichier .PDF :
```php
$email = [
'FromName' => 'Mon expediteur',
'FromEmail' => 'mon@adresse.email',
'Subject' => 'Hey!',
'Text-Part' => 'Hello Humans!',
'Html-Part' => '<p>Hello Humans</p>',
'Recipients' => [
['Email' => 'mon1er@destinataire.com', 'Name' => 'destinataire1'],
['Email' => 'mon2nd@destinataire.com', 'Name' => 'destinataire2']
],
'Attachments' => [
[
'Content-type' => "application/x-pdf", // ou application/pdf ne passe pas non plus
'Filename' => "test.pdf"
]
]
];
...php
Deplus je ne trouve pas dans la documentation à quoi correspond la dernière propriété content de l'objet Attachement. Pour information voici le code erreur
...php
PHP Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error response [url] https://api.mailjet.com/v3/send [status code] 500 [reason phrase] Invalid stream operation' in /var/www/crons/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
Stack trace:
#0 /var/www/crons/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 /var/www/crons/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(109): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 /var/www/crons/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 /var/www/crons/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#4 /var/www/crons/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->G in /var/www/crons/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89
...php

**Comment by GuillaumeBadi** [comment]
Hey @bamboolix !

La propriete `content` correspond au contenu de ton fichier en base64. Ca devrait resoudre ton probleme. Si ce n'est pas le cas, n'hesite pas a me ping :)

``` php


$content = fread(fopen('./test.pdf', "r"), filesize('./test.pdf'));

$email = [
    'FromEmail' => 'sender email',
    'Subject' => 'Hey!',
    'Text-Part' => 'Hello Humans!',
    'Recipients' => [['Email' => 'test@mailjet.com', 'Name' => 'test recipient']],
    'Attachments' => [
        [
                'Content-type' => "application/pdf",
                'Filename' => "test.pdf",
                'Content' => base64_encode($content)
        ]
    ]
];

$response = $mailjet->post(Resources::$Email, ['body' => $email]);

var_dump($response->getData());

```

Guillaume.

**Comment by bamboolix** [comment]
Wunderbar ! Du premier coup : 

Pour ceux qui auraient besoin d'une réponse : 
...php
$path = '/var/www/crons/test.pdf';
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);
$base64 = base64_encode($data);

    'Attachments' => [
        [
            'Content-type' => "application/x-pdf",
            'Filename' => "test.pdf",
	     'content' => $base64
        ]
    ]
...

Merci @GuillaumeBadi

**Comment by GuillaumeBadi** [comment]
Au plaisir ! :) :+1:
